<?xml version="1.0" encoding="utf-8"?><Database Name="LTW_Login" Class="DataLoginDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI\TRIEUHIEU;Initial Catalog=LTW_Login;User ID=sa" SettingsObjectName="bx.Properties.Settings" SettingsPropertyName="LTW_LoginConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DataLogin" Member="DataLogins">
    <Type Name="DataLogin">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>